filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
 
processors:
# - add_cloud_metadata: ~          # cloud hosts
- add_host_metadata:             # on-premises hosts
    cache.ttl: 5m
- decode_json_fields:
    fields: ["log", "message"]
    target: "json"
    overwrite_keys: true
    add_error_key: true

output.elasticsearch:
  hosts: ["http://0.0.0.0:9200"]
  username: filebeat_internal
  password: changeme
  index: "foo-%{+yyyy.MM.dd}"

logging.to_syslog: true          # filebeat>=8.5.1
logging.metrics.enabled: false

setup.template.name: "foo"
setup.template.pattern: "foo-*"
setup.ilm.enabled: false
